model_versions: "v1.0.0"
choosen_method: "Random Forest"
methods:
  - name: "Logistic Regression"
    config:
      max_iter: 1000
  - name: "Random Forest"
    config:
      n_estimators: 200
      max_depth: 5
  - name: "SVM"
    config:
      C: 1.0
      kernel: "rbf"
  - name: "Gradient Boosting Classifier"
    config:
      n_estimators: 100
      learning_rate: 0.1
      criterion: 'friedman_mse'